import{a as b,S as v,i}from"./assets/vendor-DQvd0HNi.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();async function m(o,a=1){const t="https://pixabay.com/api/",r={key:"55046139-0926bc9d71fa83e7a7b72101e",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:a,per_page:15};try{return(await b.get(t,{params:r})).data}catch(n){throw n}}const h=document.querySelector(".loader"),y=document.querySelector(".gallery"),p=document.querySelector(".load-more"),P=new v(".gallery a",{captionsData:"alt",captionDelay:250});function g(o){const a=o.map(t=>`
      <li class="gallery-item">
        <a href="${t.largeImageURL}">
          <img src="${t.webformatURL}" alt="${t.tags}" />
        </a>
        <div class="info">
          <p>Likes: ${t.likes}</p>
          <p>Views: ${t.views}</p>
          <p>Comments: ${t.comments}</p>
          <p>Downloads: ${t.downloads}</p>
        </div>
      </li>`).join("");y.insertAdjacentHTML("beforeend",a),P.refresh()}function E(){y.innerHTML=""}function L(){h.classList.remove("hidden")}function l(){h.classList.add("hidden")}function w(){p.classList.remove("hidden")}function d(){p.classList.add("hidden")}const S=document.querySelector(".form"),q=document.querySelector(".load-more");let u="",c=1,f=0;S.addEventListener("submit",async o=>{o.preventDefault(),d(),E();const t=new FormData(o.target).get("search-text");if(!t){i.error({message:"Please enter a search term"});return}u=t.trim(),c=1,L();try{const s=await m(u,c);if(l(),s.hits.length===0){i.info({message:"Sorry, there are no images matching your search query. Please try again!"});return}f=s.totalHits,g(s.hits),f>c*15?w():(d(),i.info({message:"We're sorry, but you've reached the end of search results."}))}catch(s){l(),i.error({message:"Something went wrong. Please try again later."}),console.error(s)}});q.addEventListener("click",async()=>{c+=1,d(),L();try{const o=await m(u,c);l(),g(o.hits);const{height:a}=document.querySelector(".gallery a").getBoundingClientRect();window.scrollBy({top:a*2,behavior:"smooth"}),c*15<f?w():(d(),i.info({message:"We're sorry, but you've reached the end of search results."}))}catch(o){l(),i.error({message:"Something went wrong. Try again later."}),console.error(o)}});
//# sourceMappingURL=index.js.map
