import{a as w,S as b,i}from"./assets/vendor-DQvd0HNi.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();async function u(o,a=1){const t="https://pixabay.com/api/",r={key:"55046139-0926bc9d71fa83e7a7b72101e",q:o,image_type:"photo",orientation:"horizontal",safesearch:"true",page:a,per_page:15};try{return(await w.get(t,{params:r})).data}catch(n){throw n}}const f=document.querySelector(".loader"),m=document.querySelector(".gallery"),h=document.querySelector(".load-more"),P=new b(".gallery a",{captionsData:"alt",captionDelay:250});function y(o){const a=o.map(t=>`
      <li class="gallery-item">
        <a href="${t.largeImageURL}">
          <img src="${t.webformatURL}" alt="${t.tags}" />
        </a>
        <div class="info">
          <p>Likes: ${t.likes}</p>
          <p>Views: ${t.views}</p>
          <p>Comments: ${t.comments}</p>
          <p>Downloads: ${t.downloads}</p>
        </div>
      </li>`).join("");m.insertAdjacentHTML("beforeend",a),P.refresh()}function v(){m.innerHTML=""}function p(){f.classList.remove("hidden")}function l(){f.classList.add("hidden")}function E(){h.classList.remove("hidden")}function g(){h.classList.add("hidden")}const S=document.querySelector(".form"),q=document.querySelector(".load-more");let d="",c=1,L=0;S.addEventListener("submit",async o=>{o.preventDefault(),g(),v();const t=new FormData(o.target).get("search-text");if(!t){i.error({message:"Please enter a search term"});return}d=t.trim(),c=1,p();try{const s=await u(d,c);if(l(),s.hits.length===0){i.info({message:"Sorry, there are no images matching your search query. Please try again!"});return}L=s.totalHits,y(s.hits),E()}catch(s){l(),i.error({message:"Something went wrong. Please try again later."}),console.error(s)}});q.addEventListener("click",async()=>{c+=1,p();try{const o=await u(d,c);l(),y(o.hits);const{height:a}=document.querySelector(".gallery a").getBoundingClientRect();window.scrollBy({top:a*2,behavior:"smooth"}),c*15>=L&&(g(),i.info({message:"We're sorry, but you've reached the end of search results."}))}catch(o){l(),i.error({message:"Something went wrong. Try again later."}),console.error(o)}});
//# sourceMappingURL=index.js.map
